#!/usr/bin/env python3
"""A single 20mm cube in PrusaSlicer / Slic3r PE 3MF flavor — the shape
`bookend.3mf` (a real Slic3r PE export) uses:

  3D/3dmodel.model             — standard 3MF core geometry, `slic3rpe`
                                 namespace + a Version3mf metadata marker
  Metadata/Slic3r_PE_model.config — Prusa per-object metadata: `<object id>`
                                 with `<metadata type="object" key="name">`
                                 and a `<volume firstid/lastid>` block
                                 (NOT the BBS `<part>`/`model_settings.config`)

Exercises the geometry import path for Prusa 3MFs (no BBS
`model_settings.config`, no `project_settings.config`) and the object-name
lift from `Slic3r_PE_model.config`.

Output: `prusa-cube.3mf` next to this script. Regenerate via
  python3 src-tauri/tests/fixtures/3mf/prusa-cube.py
"""
import zipfile
from pathlib import Path
OUT = Path(__file__).with_suffix(".3mf")

def cube(size):
    h = size/2
    faces = [
        ([-h,-h,h],[h,-h,h],[h,h,h],[-h,h,h]),
        ([-h,h,-h],[h,h,-h],[h,-h,-h],[-h,-h,-h]),
        ([h,-h,-h],[h,h,-h],[h,h,h],[h,-h,h]),
        ([-h,h,-h],[-h,-h,-h],[-h,-h,h],[-h,h,h]),
        ([h,h,-h],[-h,h,-h],[-h,h,h],[h,h,h]),
        ([-h,-h,-h],[h,-h,-h],[h,-h,h],[-h,-h,h]),
    ]
    v, t = [], []
    for f in faces:
        b = len(v); v.extend(f)
        t += [(b,b+1,b+2),(b,b+2,b+3)]
    return v, t

v, t = cube(20.0)
vx = "".join(f'<vertex x="{x}" y="{y}" z="{z}"/>' for x,y,z in v)
tx = "".join(f'<triangle v1="{a}" v2="{b}" v3="{c}"/>' for a,b,c in t)

# Standard 3MF core geometry with the slic3rpe namespace, exactly as a
# Slic3r PE export writes it.
model = (
    '<?xml version="1.0" encoding="UTF-8"?>\n'
    '<model unit="millimeter" xml:lang="en-US"'
    ' xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02"'
    ' xmlns:slic3rpe="http://schemas.slic3r.org/3mf/2017/06">\n'
    ' <metadata name="slic3rpe:Version3mf">1</metadata>\n'
    ' <metadata name="Application">PrusaSlicer-fixture</metadata>\n'
    ' <resources>\n'
    f'  <object id="1" type="model">\n   <mesh>\n    <vertices>{vx}</vertices>\n'
    f'    <triangles>{tx}</triangles>\n   </mesh>\n  </object>\n'
    ' </resources>\n <build>\n'
    '  <item objectid="1" transform="1 0 0 0 1 0 0 0 1 125 105 10" printable="1"/>\n'
    ' </build>\n</model>\n'
)

# Prusa per-object metadata: object name + a volume block (the volume's own
# name metadata must NOT be picked up as the object name — the parser filters
# on type="object").
pe = (
    '<?xml version="1.0" encoding="UTF-8"?>\n<config>\n'
    ' <object id="1">\n'
    '  <metadata type="object" key="name" value="Heart-shaped Bookend"/>\n'
    '  <volume firstid="0" lastid="11">\n'
    '   <metadata type="volume" key="name" value="bookend.stl"/>\n'
    '   <metadata type="volume" key="volume_type" value="ModelPart"/>\n'
    '  </volume>\n'
    ' </object>\n</config>\n'
)

# Global print config, PrusaSlicer INI flavor: every line is `; key = value`.
# The bookend is a shell-only print. Carries the geometry-intent keys (shells,
# walls, infill, raft/brim, seam) + noise that must NOT be adopted: printer/temp
# keys, and the print-GLOBAL skirt/spiral keys (object-override gate drops them).
pe_config = (
    "; generated by PrusaSlicer 2.2.0 fixture\n"
    "; bed_shape = 0x0,250x0,250x210,0x210\n"
    "; bottom_fill_pattern = rectilinear\n"
    "; bottom_solid_layers = 0\n"
    "; brim_width = 0\n"
    "; fill_angle = 45\n"
    "; fill_density = 15%\n"
    "; fill_pattern = honeycomb\n"
    "; infill_overlap = 25%\n"
    "; nozzle_temperature = 240\n"
    "; perimeters = 6\n"
    "; raft_layers = 0\n"
    "; seam_position = nearest\n"
    "; skirts = 1\n"
    "; spiral_vase = 0\n"
    "; top_fill_pattern = rectilinear\n"
    "; top_solid_layers = 0\n"
)

with zipfile.ZipFile(OUT, "w", compression=zipfile.ZIP_DEFLATED) as z:
    z.writestr("[Content_Types].xml", '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">\n <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>\n <Default Extension="model" ContentType="application/vnd.ms-package.3dmanufacturing-3dmodel+xml"/>\n <Default Extension="config" ContentType="application/vnd.ms-package.3dmanufacturing-config+xml"/>\n</Types>\n')
    z.writestr("_rels/.rels", '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">\n <Relationship Target="/3D/3dmodel.model" Id="rel-1" Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/>\n</Relationships>\n')
    z.writestr("3D/3dmodel.model", model)
    z.writestr("Metadata/Slic3r_PE_model.config", pe)
    z.writestr("Metadata/Slic3r_PE.config", pe_config)
print(f"wrote {OUT}")
