//! Per-bucket vendor profile library (PR-S-4).
//!
//! Loads the bundled vendor cascade fragments and exposes them by
//! `(bucket, slug)` to the runtime composer (PR-S-5). Each fragment is
//! a small cascade TOML containing the keys for one bucket of one
//! source profile (e.g. the printer-bucket subset of the Bambu A1 mini
//! 0.4 nozzle JSON).
//!
//! Fragments are generated by `scripts/convert_per_bucket.py` from
//! OrcaSlicer's per-bucket profile JSONs and committed under
//! `profiles/vendor/<vendor>/{printer,filament,process}/<slug>.toml`.
//! Each is `include_str!`-bundled here at compile time — packaged
//! builds don't depend on resource lookup at runtime.
//!
//! See `docs/design/settings-model.md` §4 / §5 for the runtime
//! composition story; this module is the source-of-bucket-fragments
//! that the composer layers.

use std::path::Path;

use crate::core::cascade::loader::{parse_cascade_str, CascadeLoadError};
use crate::core::cascade::types::Cascade;

/// One bundled per-bucket fragment.
#[derive(Debug, Clone, Copy)]
struct BundledFragment {
    bucket: Bucket,
    slug: &'static str,
    toml: &'static str,
    /// Stable filesystem path used as the `SourceLocation` when the
    /// fragment is parsed — keeps cascade trace output readable.
    source_path: &'static str,
}

/// Which preset bucket a fragment belongs to. Mirrors
/// [`slic3r_ffi::OptBucket`]; kept as its own enum here because this
/// module loads cascade fragments rather than OptionDefs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Bucket {
    Printer,
    Filament,
    Process,
}

const FRAGMENTS: &[BundledFragment] = &[
    // ----- Bambi (Bambu A1 mini 0.4 nozzle + PLA Basic + 0.20mm Standard) -----
    BundledFragment {
        bucket: Bucket::Printer,
        slug: "bambu-lab-a1-mini-0.4-nozzle",
        toml: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../profiles/vendor/bbl/printer/bambu-lab-a1-mini-0.4-nozzle.toml"
        )),
        source_path: "profiles/vendor/bbl/printer/bambu-lab-a1-mini-0.4-nozzle.toml",
    },
    BundledFragment {
        bucket: Bucket::Filament,
        slug: "bambu-pla-basic-bbl-a1m",
        toml: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../profiles/vendor/bbl/filament/bambu-pla-basic-bbl-a1m.toml"
        )),
        source_path: "profiles/vendor/bbl/filament/bambu-pla-basic-bbl-a1m.toml",
    },
    BundledFragment {
        bucket: Bucket::Process,
        slug: "0.20mm-standard-bbl-a1m",
        toml: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../profiles/vendor/bbl/process/0.20mm-standard-bbl-a1m.toml"
        )),
        source_path: "profiles/vendor/bbl/process/0.20mm-standard-bbl-a1m.toml",
    },
    // ----- Snappy (Snapmaker U1 0.4 nozzle + PLA + 0.20 Standard) -----
    BundledFragment {
        bucket: Bucket::Printer,
        slug: "snapmaker-u1-0.4-nozzle",
        toml: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../profiles/vendor/snapmaker/printer/snapmaker-u1-0.4-nozzle.toml"
        )),
        source_path: "profiles/vendor/snapmaker/printer/snapmaker-u1-0.4-nozzle.toml",
    },
    BundledFragment {
        bucket: Bucket::Filament,
        slug: "snapmaker-pla-u1",
        toml: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../profiles/vendor/snapmaker/filament/snapmaker-pla-u1.toml"
        )),
        source_path: "profiles/vendor/snapmaker/filament/snapmaker-pla-u1.toml",
    },
    BundledFragment {
        bucket: Bucket::Process,
        slug: "0.20-standard-snapmaker-u1-0.4-nozzle",
        toml: include_str!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../profiles/vendor/snapmaker/process/0.20-standard-snapmaker-u1-0.4-nozzle.toml"
        )),
        source_path: "profiles/vendor/snapmaker/process/0.20-standard-snapmaker-u1-0.4-nozzle.toml",
    },
];

/// Parse a bundled fragment into a [`Cascade`]. Returns `None` if the
/// `(bucket, slug)` doesn't match any bundled entry. Panics on parse
/// failure — the fragments are compile-time constants generated by the
/// converter, so a parse failure means a malformed bundled artifact and
/// the binary shouldn't have shipped.
pub fn load_fragment(bucket: Bucket, slug: &str) -> Option<Cascade> {
    let entry = FRAGMENTS
        .iter()
        .find(|f| f.bucket == bucket && f.slug == slug)?;
    let path = Path::new(entry.source_path);
    let rules = parse_cascade_str(entry.toml, path)
        .unwrap_or_else(|e: CascadeLoadError| panic!("bundled fragment {}: {e}", entry.slug));
    Some(Cascade { rules })
}

/// Enumerate all bundled fragments for a bucket. Returns slug strings
/// in insertion order. Used by tests and (post-MVP) by a future
/// vendor-fragment browser surface.
pub fn list_slugs(bucket: Bucket) -> Vec<&'static str> {
    FRAGMENTS
        .iter()
        .filter(|f| f.bucket == bucket)
        .map(|f| f.slug)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_six_fragments_parse() {
        // Each bundled fragment must round-trip through the cascade
        // parser. A parse failure here usually means the converter
        // produced an invalid TOML structure — re-run
        // scripts/convert_per_bucket.py and inspect the offending file.
        for bucket in [Bucket::Printer, Bucket::Filament, Bucket::Process] {
            for slug in list_slugs(bucket) {
                let cascade = load_fragment(bucket, slug)
                    .unwrap_or_else(|| panic!("missing fragment ({bucket:?}, {slug})"));
                assert!(
                    !cascade.rules.is_empty(),
                    "fragment ({bucket:?}, {slug}) has no rules",
                );
            }
        }
    }

    #[test]
    fn bambi_printer_fragment_carries_machine_envelope() {
        // Spot-check that printer-bucket keys land in the printer
        // fragment. printable_height and machine_max_acceleration_x
        // are quintessential printer-bucket entries.
        let cascade = load_fragment(Bucket::Printer, "bambu-lab-a1-mini-0.4-nozzle")
            .expect("bambi printer fragment");
        let default_rule = &cascade.rules[0];
        assert!(
            default_rule.set.contains_key("printable_height"),
            "printable_height should be in the printer fragment",
        );
        assert!(
            default_rule.set.contains_key("machine_max_acceleration_x"),
            "machine_max_acceleration_x should be in the printer fragment",
        );
    }

    #[test]
    fn bambi_filament_fragment_carries_temps() {
        let cascade = load_fragment(Bucket::Filament, "bambu-pla-basic-bbl-a1m")
            .expect("bambi filament fragment");
        let default_rule = &cascade.rules[0];
        assert!(
            default_rule.set.contains_key("nozzle_temperature"),
            "nozzle_temperature should be in the filament fragment",
        );
        assert!(
            default_rule.set.contains_key("filament_settings_id"),
            "filament_settings_id (firmware-required) should be injected",
        );
    }

    #[test]
    fn bambi_process_fragment_carries_strategy_keys() {
        let cascade = load_fragment(Bucket::Process, "0.20mm-standard-bbl-a1m")
            .expect("bambi process fragment");
        let default_rule = &cascade.rules[0];
        assert!(
            default_rule.set.contains_key("layer_height"),
            "layer_height should be in the process fragment",
        );
        assert!(
            default_rule.set.contains_key("wall_loops"),
            "wall_loops should be in the process fragment",
        );
    }

    #[test]
    fn snappy_printer_fragment_carries_u1_envelope() {
        let cascade = load_fragment(Bucket::Printer, "snapmaker-u1-0.4-nozzle")
            .expect("snappy printer fragment");
        let default_rule = &cascade.rules[0];
        assert!(default_rule.set.contains_key("printable_height"));
        // U1 has 4 extruders — extruders_count or nozzle_diameter
        // vector encodes that on the printer side.
        assert!(default_rule.set.contains_key("nozzle_diameter"));
    }

    #[test]
    fn unknown_fragment_returns_none() {
        assert!(load_fragment(Bucket::Printer, "ghost-printer").is_none());
        assert!(load_fragment(Bucket::Filament, "imaginary-filament").is_none());
    }

    #[test]
    fn list_slugs_returns_two_per_bucket() {
        // Bambi + Snappy = 2 per bucket; assertion guards a future
        // accidental addition without a test update.
        assert_eq!(list_slugs(Bucket::Printer).len(), 2);
        assert_eq!(list_slugs(Bucket::Filament).len(), 2);
        assert_eq!(list_slugs(Bucket::Process).len(), 2);
    }
}
