#!/usr/bin/env python3
"""Bundle docs/design/ into a single standalone HTML file.

The design mockup at docs/design/ is a feature-incomplete React + Three.js
prototype that loads via Babel-in-browser. This script collapses all the
local JSX modules and the CSS into one file by inlining each
`<script type="text/babel" src="…">` and `<link rel="stylesheet" href="…">`
in `index.html`.

CDN scripts (React, ReactDOM, Babel-standalone, Three.js) and Google Fonts
stay as live network references — they're not inlined. The standalone
therefore needs an internet connection to open. If we ever need true
offline mode, fetch + inline those assets here.

Output: docs/design/n3o-slic3r-standalone.html (overwrites).

Usage:
    ./scripts/bundle-design.py

No dependencies beyond the Python standard library.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESIGN = ROOT / "docs" / "design"
SOURCE = DESIGN / "index.html"
OUTPUT = DESIGN / "n3o-slic3r-standalone.html"


def inline_jsx(match: re.Match[str]) -> str:
    path = match.group(1)
    target = DESIGN / path
    if not target.is_file():
        sys.exit(f"error: referenced JSX file not found: {path}")
    body = target.read_text()
    # Defensive: any literal </script> inside the JSX would close the
    # wrapping <script> tag early. None expected in our sources today.
    body = body.replace("</script>", "<\\/script>")
    return f'<script type="text/babel" data-source="{path}">\n{body}\n</script>'


def inline_css(match: re.Match[str]) -> str:
    path = match.group(1)
    target = DESIGN / path
    if not target.is_file():
        sys.exit(f"error: referenced CSS file not found: {path}")
    body = target.read_text()
    return f'<style data-source="{path}">\n{body}\n</style>'


def main() -> None:
    if not SOURCE.is_file():
        sys.exit(f"error: {SOURCE} not found")

    bundled = SOURCE.read_text()

    bundled = re.sub(
        r'<script\s+type="text/babel"\s+src="([^"]+)"\s*>\s*</script>',
        inline_jsx,
        bundled,
    )
    bundled = re.sub(
        r'<link\s+rel="stylesheet"\s+href="([^"]+\.css)"\s*/?>',
        inline_css,
        bundled,
    )

    banner = (
        "<!-- Standalone bundle — generated by scripts/bundle-design.py. "
        "Local CSS + JSX inlined; React/Babel/Three.js still fetched from "
        "unpkg CDN, so this file needs internet to open. -->"
    )
    bundled = bundled.replace("<head>", "<head>\n" + banner, 1)

    OUTPUT.write_text(bundled)
    size_kb = OUTPUT.stat().st_size / 1024
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({size_kb:.1f} KB)")


if __name__ == "__main__":
    main()
