#!/usr/bin/env python3
"""Import an OrcaSlicer vendor profile into n3o-slic3r's hierarchical
vendor layout (PR-S-4 rework).

Replaces `scripts/convert_per_bucket.py` (flat per-bucket fragments).
The hierarchical layout matches the physical sub-components a printer
actually decomposes into:

  profiles/vendor/<vendor>/
  ├── printer/
  │   ├── <printer-slug>.toml              # machine globals only
  │   └── <printer-slug>/
  │       └── nozzles/
  │           ├── 0.4.toml                  # scalar per-extruder keys
  │           └── 0.6.toml
  ├── bed/
  │   └── <bed-slug>.toml                   # hand-authored, NOT generated
  ├── filament/
  │   └── <filament-slug>.toml              # unchanged from per-bucket model
  └── process/
      └── <process-slug>.toml               # unchanged from per-bucket model

The composer (`core::profile_library`) assembles a per-slice cascade
from `printer.toml + N × nozzle.toml (zipped into vectors) + bed.toml
+ process.toml + filament.toml`. Bed.toml is intentionally NOT
generated by this script — bed-temperature data lives in the filament
profile (per-bed-type arrays) and the adapter expands them at slice
time; bed.toml is just identity + libslic3r `curr_bed_type` value,
authored by hand in profiles/vendor/<vendor>/bed/.

Key derivation rules:

- **printer.toml** = inheritance walk starting at the family base
  (the parent of the user-specified machine leaf), filtered to drop
  per-extruder keys (those live in nozzles/) and BBS-firmware-only
  keys (apply_bbs_filter from the legacy converter).
- **nozzles/<sku>.toml** = the leaf machine JSON's OWN keys (not
  inherited), filtered to extruder-key set only. Per-extruder arrays
  are collapsed to scalars; heterogeneous arrays error out (would
  need a different import strategy). Machine-global overrides in the
  leaf are dropped per the design (the printer's family base is
  authoritative; leaf-only globals are import-time noise we accept
  losing in exchange for a coherent model).
- **filament/process** = inheritance walks (same as legacy converter).

Run example for Bambi:

    scripts/convert_vendor_profile.py \\
        --vendor BBL \\
        --machine "Bambu Lab A1 mini 0.4 nozzle" \\
        --printer-slug bambu-lab-a1-mini \\
        --filament "Bambu PLA Basic @BBL A1M" \\
        --process "0.20mm Standard @BBL A1M" \\
        --out-dir profiles/vendor/bbl
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# Reuse inheritance walker + BBS filter from the legacy converter.
sys.path.insert(0, str(Path(__file__).resolve().parent / "spikes"))
from convert_bbs_profile import (  # type: ignore[import-not-found]
    apply_bbs_filter,
    find_by_name,
    flatten_inheritance,
    load_json,
    value_to_toml,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PROFILES_ROOT = REPO_ROOT / "external/OrcaSlicer/resources/profiles"
PRINT_CONFIG_CPP = REPO_ROOT / "external/OrcaSlicer/src/libslic3r/PrintConfig.cpp"

EXTRUDER_KEYS_BLOCK_RX = re.compile(
    r'm_extruder_option_keys\s*=\s*\{(.*?)\};',
    re.DOTALL,
)
STRING_LITERAL = re.compile(r'"([A-Za-z_][A-Za-z0-9_]*)"')
# `add("<key>", coStrings)` lines in PrintConfig.cpp — the canonical
# list of libslic3r `ConfigOptionStrings` keys. Used to pick the
# right list-serialization form in value_to_toml (semicolon +
# cstyle-escape for these; comma for everything else).
STRINGS_KEY_RX = re.compile(r'add\(\s*"([A-Za-z_][A-Za-z0-9_]*)"\s*,\s*coStrings\b')
# JSON-side metadata that's structural (inheritance, instantiation,
# catalog name) — NOT real libslic3r config keys. These get dropped
# from every fragment.
#
# `printer_model` is INTENTIONALLY NOT in this set despite looking
# meta-ish: libslic3r's FFI shim sets `is_BBL_printer()` by checking
# whether `printer_model` starts with "Bambu Lab", which gates
# Bambu-specific validation bypasses (e.g. skipping the relative-E
# G92-in-layer-gcode check that Bambu firmware handles differently
# from generic Marlin). Dropping it makes Bambu printers fail
# Marlin-only validations they shouldn't be subject to.
META_KEYS = {
    "type", "name", "inherits", "from", "setting_id", "instantiation",
    "printer_variant",
}


def _safe_rel(p: Path) -> Path:
    try:
        return p.relative_to(REPO_ROOT)
    except ValueError:
        return p


def load_extruder_keys() -> set[str]:
    """Scrape `m_extruder_option_keys` out of upstream PrintConfig.cpp.

    These are the printer-bucket keys libslic3r stores as per-extruder
    `Vec<T>` at runtime; the hierarchical layout splits them into per-
    nozzle fragments so the composer can zip them back into vectors at
    slice time.
    """
    text = PRINT_CONFIG_CPP.read_text()
    match = EXTRUDER_KEYS_BLOCK_RX.search(text)
    if not match:
        sys.exit(
            f"m_extruder_option_keys block not found in {PRINT_CONFIG_CPP}; "
            "upstream layout changed?"
        )
    return {m.group(1) for m in STRING_LITERAL.finditer(match.group(1))}


def load_strings_keys() -> set[str]:
    """Scrape every `add("<key>", coStrings)` registration from upstream
    PrintConfig.cpp.

    These keys serialize with libslic3r's `escape_strings_cstyle`
    convention (semicolon-separated, c-style-escaped per entry) — not
    the comma-separated form coFloats/coInts/coPercents use. The
    converter consults this set in `value_to_toml` to pick the right
    list-flattening form; getting it wrong silently corrupts keys like
    `small_area_infill_flow_compensation_model` whose entries are
    themselves comma-separated.
    """
    text = PRINT_CONFIG_CPP.read_text()
    keys = set(STRINGS_KEY_RX.findall(text))
    if not keys:
        sys.exit(
            f"no `add(...coStrings)` registrations found in {PRINT_CONFIG_CPP}; "
            "upstream layout changed?"
        )
    return keys


def slugify(name: str) -> str:
    s = name.lower()
    s = re.sub(r"[@()_/\s]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s


def scalarize(value, *, key: str) -> str:
    """Collapse a per-extruder array to a scalar.

    OrcaSlicer stores per-extruder values as JSON arrays even when all
    entries are identical (e.g. U1's `nozzle_diameter:
    ["0.4","0.4","0.4","0.4"]`). The hierarchical layout wants ONE
    scalar per nozzle.toml — the composer replicates it across all
    extruders at slice time. Refuse heterogeneous arrays; they'd
    require a different import strategy (mixed-nozzle preset).
    """
    if isinstance(value, list):
        distinct = set(value)
        if len(distinct) > 1:
            sys.exit(
                f"heterogeneous per-extruder array for `{key}`: {value!r}; "
                "this leaf represents a mixed-nozzle preset and can't be "
                "imported as a single nozzle SKU. Author each nozzle SKU "
                "separately or hand-tune after import."
            )
        if not value:
            return ""
        return value[0]
    # Already a scalar — shouldn't happen for extruder keys in Orca's
    # JSON shape, but be tolerant.
    return value if isinstance(value, str) else str(value)


def write_toml(
    path: Path,
    header: list[str],
    pairs: dict,
    *,
    strings_keys: set[str],
) -> None:
    lines: list[str] = []
    for line in header:
        lines.append(f"# {line}")
    lines.append("")
    for key in sorted(pairs):
        rendered = value_to_toml(pairs[key], key=key, strings_keys=strings_keys)
        lines.append(f"{key} = {rendered}")
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines))


def emit_printer_fragment(
    args, vendor_dir: Path, leaf_data: dict, extruder_keys: set[str],
    strings_keys: set[str], printer_slug: str,
) -> None:
    """printer.toml = inheritance walk from the CANONICAL leaf, minus
    per-extruder keys.

    "Canonical leaf" is the `--machine` argument's leaf. We use it as
    the source of machine globals (printable_area, machine_max_*,
    start_gcode, etc.) because OrcaSlicer's family bases (e.g.
    `fdm_bbl_3dp_001_common`) are SHARED across multiple printer models
    in the same family — their machine-globals are X1C-shaped defaults
    that each A1/A1 mini/etc. leaf overrides with the right
    per-printer-model values. Inheriting from the family base alone
    would give A1 mini X1C-sized printable_area.

    Per-extruder keys are stripped here (they go to nozzles/<sku>.toml).
    The non-canonical extra nozzle leaves contribute only their per-
    extruder scalars to their respective nozzle.toml; their machine-
    global tweaks are dropped (per the design — that's the rule against
    per-nozzle machine-global drift).
    """
    canonical_leaf_name = args.machine
    canonical_leaf_path = find_by_name(vendor_dir, "machine", canonical_leaf_name)

    walked = flatten_inheritance(canonical_leaf_path, "machine", vendor_dir)
    filtered, _drops, _renames = apply_bbs_filter(walked)
    # Drop per-extruder keys (live in nozzles/) + meta keys.
    machine_globals = {
        k: v for k, v in filtered.items()
        if k not in extruder_keys and k not in META_KEYS
    }
    # Inject the printer_settings_id firmware-required key.
    machine_globals["printer_settings_id"] = canonical_leaf_name

    out_path = args.out_dir / "printer" / f"{printer_slug}.toml"
    header = [
        f"{canonical_leaf_name} — printer (machine globals)",
        "",
        "AUTO-GENERATED by scripts/convert_vendor_profile.py from canonical leaf:",
        f"  {_safe_rel(canonical_leaf_path)}",
        "Per-extruder keys live in nozzles/<sku>.toml. Non-canonical nozzle",
        "leaves contribute only per-extruder scalars to their own nozzle.toml;",
        "their machine-global overrides are intentionally dropped per the",
        "settings-model design (manually refine after import if needed).",
    ]
    write_toml(out_path, header, machine_globals, strings_keys=strings_keys)
    print(f"wrote {_safe_rel(out_path)} ({len(machine_globals)} keys)")


def emit_nozzle_fragment(
    args, vendor_dir: Path, leaf_name: str, extruder_keys: set[str],
    strings_keys: set[str], printer_slug: str,
) -> None:
    """nozzles/<sku>.toml = ALL per-extruder keys for this nozzle, scalarized.

    Walks inheritance from the leaf (same as the printer fragment) and
    filters to the per-extruder key set. This gives each nozzle.toml a
    *complete* per-extruder spec — different SKUs can have legitimately
    different retraction/layer-height/extruder-type values, and the
    composer reads one nozzle.toml per extruder.

    The leaf's `printer_variant` is the SKU. The leaf's machine-global
    overrides (auxiliary_fan, machine_max_jerk_z, etc.) are
    intentionally NOT here — those would land in printer.toml from the
    canonical leaf's walk and are out-of-scope for nozzle deltas per
    the design.
    """
    leaf_path = find_by_name(vendor_dir, "machine", leaf_name)
    leaf_data = load_json(leaf_path)
    sku = leaf_data.get("printer_variant")
    if not sku:
        sys.exit(f"leaf `{leaf_name}` missing `printer_variant`; can't derive nozzle SKU")

    walked = flatten_inheritance(leaf_path, "machine", vendor_dir)
    filtered, _drops, _renames = apply_bbs_filter(walked)
    nozzle_scalars = {
        k: scalarize(v, key=k)
        for k, v in filtered.items()
        if k in extruder_keys and k not in META_KEYS
    }

    out_path = args.out_dir / "printer" / printer_slug / "nozzles" / f"{sku}.toml"
    header = [
        f"{leaf_name} → nozzle SKU `{sku}`",
        "",
        "AUTO-GENERATED by scripts/convert_vendor_profile.py from leaf:",
        f"  {_safe_rel(leaf_path)}",
        "Complete per-extruder spec for this nozzle SKU — the composer",
        "zips one of these into extruders_count-length vectors at slice",
        "time (one file loaded per extruder, scalars merged into vectors).",
    ]
    write_toml(out_path, header, nozzle_scalars, strings_keys=strings_keys)
    print(f"wrote {_safe_rel(out_path)} ({len(nozzle_scalars)} keys)")


def emit_filament_fragment(args, vendor_dir: Path, strings_keys: set[str]) -> None:
    path = find_by_name(vendor_dir, "filament", args.filament)
    walked = flatten_inheritance(path, "filament", vendor_dir)
    filtered, _drops, _renames = apply_bbs_filter(walked)
    filtered = {k: v for k, v in filtered.items() if k not in META_KEYS}
    filtered["filament_settings_id"] = args.filament
    slug = slugify(args.filament)
    out_path = args.out_dir / "filament" / f"{slug}.toml"
    header = [
        f"{args.filament} — filament",
        "",
        f"AUTO-GENERATED by scripts/convert_vendor_profile.py from: {_safe_rel(path)}",
    ]
    write_toml(out_path, header, filtered, strings_keys=strings_keys)
    print(f"wrote {_safe_rel(out_path)} ({len(filtered)} keys)")


def emit_process_fragment(args, vendor_dir: Path, strings_keys: set[str]) -> None:
    path = find_by_name(vendor_dir, "process", args.process)
    walked = flatten_inheritance(path, "process", vendor_dir)
    filtered, _drops, _renames = apply_bbs_filter(walked)
    filtered = {k: v for k, v in filtered.items() if k not in META_KEYS}
    filtered["print_settings_id"] = args.process
    slug = slugify(args.process)
    out_path = args.out_dir / "process" / f"{slug}.toml"
    header = [
        f"{args.process} — process",
        "",
        f"AUTO-GENERATED by scripts/convert_vendor_profile.py from: {_safe_rel(path)}",
    ]
    write_toml(out_path, header, filtered, strings_keys=strings_keys)
    print(f"wrote {_safe_rel(out_path)} ({len(filtered)} keys)")


def main() -> None:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--vendor", required=True,
                   help="Vendor directory under --profiles-root (e.g. BBL, Snapmaker)")
    p.add_argument("--machine", required=True,
                   help="Machine leaf display name (e.g. 'Bambu Lab A1 mini 0.4 nozzle'). "
                        "Drives both the printer.toml (via its family base) and the "
                        "primary nozzle fragment.")
    p.add_argument("--printer-slug", required=True,
                   help="Filesystem slug for printer/<slug>.toml + printer/<slug>/...")
    p.add_argument("--extra-nozzles", nargs="*", default=[],
                   help="Additional machine leaves to emit as nozzles/<sku>.toml")
    p.add_argument("--filament", required=True,
                   help="Filament profile display name")
    p.add_argument("--process", required=True,
                   help="Process profile display name")
    p.add_argument("--out-dir", required=True, type=Path,
                   help="Vendor output directory (printer/, bed/, filament/, process/ subdirs)")
    p.add_argument("--profiles-root", type=Path, default=DEFAULT_PROFILES_ROOT)
    args = p.parse_args()

    vendor_dir = args.profiles_root / args.vendor
    if not vendor_dir.is_dir():
        sys.exit(f"vendor directory missing: {vendor_dir}")

    extruder_keys = load_extruder_keys()
    strings_keys = load_strings_keys()
    leaf_path = find_by_name(vendor_dir, "machine", args.machine)
    leaf_data = load_json(leaf_path)

    # printer.toml from the leaf's family base.
    emit_printer_fragment(
        args, vendor_dir, leaf_data, extruder_keys, strings_keys, args.printer_slug
    )

    # One nozzles/<sku>.toml per requested nozzle variant.
    for nozzle_leaf in [args.machine] + args.extra_nozzles:
        emit_nozzle_fragment(
            args, vendor_dir, nozzle_leaf, extruder_keys, strings_keys, args.printer_slug
        )

    # filament/process — unchanged from the legacy per-bucket layout.
    emit_filament_fragment(args, vendor_dir, strings_keys)
    emit_process_fragment(args, vendor_dir, strings_keys)

    print("\nNote: bed.toml files are hand-authored under "
          f"{_safe_rel(args.out_dir / 'bed')}; the converter does NOT generate them.")


if __name__ == "__main__":
    main()
