#!/usr/bin/env python3
"""Derive a patched variant of a bundled printer profile.

Some printers we want to ship aren't what the vendor ships — the
canonical case is a Klipper-converted machine whose upstream Orca
profile only exists in Marlin form. Hand-editing the imported profile
is unsustainable (the next `sync_orcaslicer.sh` re-import clobbers
it), so variants are *derived*: the base profile stays a verbatim
import, and this script regenerates the variant from it, applying a
declared set of patches. Run it after `import_machine_profile.py` +
`import_processes.py` (it copies their committed output);
`sync_orcaslicer.sh` sequences that.

What it does, per file class:

  machine.toml   — copied with `printer_model` suffixed (the variant
                   needs its own catalog display name AND cascade
                   predicate key) and each `--set key=value` scalar
                   rewritten in place. Comments and hand-preserved
                   scalar blocks survive (textual copy + line patch).
  nozzles/, beds/ — copied verbatim.
  processes/     — copied with `when.printer.model` predicates
                   rewritten from the base model to the variant model,
                   so the fragments keep firing under the new name.
  model.toml     — NOT generated: printer metadata (driver_kind,
                   experimental, toolheads) is hand-curated per
                   variant, same as for imported printers. The script
                   warns when it's missing.

Patches only apply to single-line scalar keys (`key = "value"`); a
`--set` targeting a missing or multi-line key aborts loudly rather
than silently shipping an unpatched variant.

Usage:
  derive_printer_variant.py \\
      --base resources/profiles/creality/printer/creality-ender-3-s1 \\
      --slug creality-ender-3-s1-klipper \\
      --model-suffix " (Klipper)" \\
      --set gcode_flavor=klipper
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from _atomic_io import atomic_write_text


def scalar_line_re(key: str) -> re.Pattern[str]:
    return re.compile(rf'^{re.escape(key)} = "(.*)"$', re.MULTILINE)


def read_model(machine_toml: str, base_dir: Path) -> str:
    m = scalar_line_re("printer_model").search(machine_toml)
    if not m:
        sys.exit(f"error: {base_dir}/machine.toml has no single-line `printer_model` scalar")
    return m.group(1)


def patch_machine(
    text: str,
    *,
    base_dir: Path,
    base_model: str,
    variant_model: str,
    sets: dict[str, str],
) -> str:
    header = (
        f"# DERIVED variant of `{base_dir.name}` — regenerated by\n"
        f"# scripts/derive_printer_variant.py; edit the base profile or the\n"
        f"# derivation call in scripts/sync_orcaslicer.sh, not this file.\n"
    )
    out = header + text
    replacements = {"printer_model": variant_model, **sets}
    for key, value in replacements.items():
        pattern = scalar_line_re(key)
        if not pattern.search(out):
            sys.exit(
                f"error: `{key}` is not a single-line scalar in "
                f"{base_dir}/machine.toml — cannot patch the variant"
            )
        out = pattern.sub(f'{key} = "{value}"', out, count=1)
    return out


def rewrite_process(text: str, base_model: str, variant_model: str) -> str:
    """Rewrite `when.printer.model` predicates (string or array form)
    from the base model name to the variant's."""
    def rewrite_line(m: re.Match[str]) -> str:
        return m.group(0).replace(f'"{base_model}"', f'"{variant_model}"')

    return re.sub(
        r'^when\.printer\.model = .*$',
        rewrite_line,
        text,
        flags=re.MULTILINE,
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", required=True, type=Path)
    ap.add_argument("--slug", required=True)
    ap.add_argument("--model-suffix", required=True)
    ap.add_argument(
        "--set",
        dest="sets",
        action="append",
        default=[],
        metavar="KEY=VALUE",
        help="machine.toml scalar to rewrite in the variant (repeatable)",
    )
    args = ap.parse_args()

    base: Path = args.base
    if not (base / "machine.toml").exists():
        sys.exit(f"error: {base} has no machine.toml")
    out_dir = base.parent / args.slug
    sets: dict[str, str] = {}
    for entry in args.sets:
        key, sep, value = entry.partition("=")
        if not sep or not key:
            sys.exit(f"error: --set expects KEY=VALUE, got `{entry}`")
        sets[key] = value

    machine_text = (base / "machine.toml").read_text(encoding="utf-8")
    base_model = read_model(machine_text, base)
    variant_model = base_model + args.model_suffix

    atomic_write_text(
        out_dir / "machine.toml",
        patch_machine(
            machine_text,
            base_dir=base,
            base_model=base_model,
            variant_model=variant_model,
            sets=sets,
        ),
    )
    copied = 1
    for sub in ("nozzles", "beds"):
        for f in sorted((base / sub).glob("*.toml")):
            atomic_write_text(out_dir / sub / f.name, f.read_text(encoding="utf-8"))
            copied += 1
    for f in sorted((base / "processes").glob("*.toml")):
        atomic_write_text(
            out_dir / "processes" / f.name,
            rewrite_process(f.read_text(encoding="utf-8"), base_model, variant_model),
        )
        copied += 1

    print(f"derived {out_dir} ({copied} files) — model `{variant_model}`")
    if not (out_dir / "model.toml").exists():
        print(
            f"note: {out_dir}/model.toml is missing — author it by hand "
            f"(driver_kind, experimental, toolheads); the library will not "
            f"load the printer without it",
            file=sys.stderr,
        )


if __name__ == "__main__":
    main()
