#!/usr/bin/env python3
"""Import an Orca/BBS process leaf JSON into our cascade-fragment TOML.

Same shape as `import_filament_profile.py`. Walks the `inherits`
chain across vendor directories (with same-vendor preference, since
different vendors keep distinct `fdm_process_common.json` files with
different values), flattens root-first, and emits a single TOML
fragment.

Backfills `print_settings_id` from the leaf's `name` field — Orca
populates that at preset-load time, not as a static JSON field, so
the cascade fragment would otherwise have no picker-visible label.

Usage:
  import_process_profile.py \\
      --root external/OrcaSlicer/resources/profiles \\
      --leaf "BBL/process/0.20mm Standard @BBL A1M.json" \\
      --out profiles/vendor/bbl/process/0.20mm-standard-bbl-a1m.toml
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ENVELOPE_KEYS = frozenset({
    "type",
    "name",
    "inherits",
    "from",
    "setting_id",
    "instantiation",
    "version",
    "renamed_from",
    "print_settings_id",  # backfilled from leaf `name` (see below)
})


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def build_process_index(root: Path) -> dict[str, list[Path]]:
    """Map `<filename-stem>` → every process JSON under any vendor's
    `process/` directory at any depth. Same name in multiple vendors is
    allowed (we resolve with same-vendor preference at lookup time)."""
    index: dict[str, list[Path]] = {}
    for vendor_dir in root.iterdir():
        if not vendor_dir.is_dir():
            continue
        process_root = vendor_dir / "process"
        if not process_root.is_dir():
            continue
        for p in process_root.rglob("*.json"):
            index.setdefault(p.stem, []).append(p)
    return index


def resolve_parent(name: str, leaf_dir: Path, index: dict[str, list[Path]]) -> Path:
    candidates = index.get(name)
    if not candidates:
        raise FileNotFoundError(
            f"inherits parent `{name}` not found in any vendor's "
            f"process/ directory"
        )
    leaf_process_root = leaf_dir
    while leaf_process_root.name != "process" and leaf_process_root.parent != leaf_process_root:
        leaf_process_root = leaf_process_root.parent
    for c in candidates:
        c_process_root = c.parent
        while c_process_root.name != "process" and c_process_root.parent != c_process_root:
            c_process_root = c_process_root.parent
        if c_process_root == leaf_process_root:
            return c
    return sorted(candidates)[0]


def flatten_inheritance(leaf: Path, index: dict[str, list[Path]]) -> tuple[dict, list[Path]]:
    """Walk inheritance from `leaf` to root, then merge root-first
    with child-wins. Returns (merged_dict, chain_paths) for the report.
    """
    chain: list[tuple[Path, dict]] = []
    visited: set[Path] = set()
    current = leaf
    while True:
        resolved = current.resolve()
        if resolved in visited:
            raise RuntimeError(f"inherits cycle through {resolved}")
        visited.add(resolved)
        doc = load_json(current)
        chain.append((current, doc))
        parent = doc.get("inherits")
        if not parent:
            break
        current = resolve_parent(parent, current.parent, index)

    merged: dict = {}
    for _, doc in reversed(chain):
        for k, v in doc.items():
            if k in ENVELOPE_KEYS:
                continue
            merged[k] = v
    return merged, [p for p, _ in chain]


def leaf_display_name(leaf: Path) -> str:
    doc = load_json(leaf)
    return doc.get("name") or leaf.stem


# ---- TOML emission --------------------------------------------------

def _toml_string(s: str) -> str:
    if "\n" in s or '"' in s or "\\" in s:
        return "'''" + s.replace("'''", "''\\''") + "'''"
    return f'"{s}"'


def value_to_toml(v: Any) -> str:
    if isinstance(v, list):
        return _toml_string(",".join(str(x) for x in v))
    return _toml_string(str(v))


def write_toml(path: Path, kv: dict, *, source: Path, chain: list[Path], root: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        f"# {kv.get('print_settings_id', source.stem)} — process cascade fragment.",
        f"# Generated by scripts/import_process_profile.py from:",
        f"#   {source.relative_to(root) if source.is_relative_to(root) else source}",
        f"# Inheritance chain (leaf → root):",
    ]
    for p in chain:
        header.append(f"#   - {p.relative_to(root) if p.is_relative_to(root) else p}")
    header.append("")
    body = [f"{k} = {value_to_toml(kv[k])}" for k in sorted(kv)]
    path.write_text("\n".join(header + body) + "\n")


# ---- Main -----------------------------------------------------------

def main() -> None:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--root", type=Path, required=True,
                    help="profiles tree root (e.g. external/OrcaSlicer/resources/profiles)")
    ap.add_argument("--leaf", required=True,
                    help="process leaf JSON path, relative to --root "
                         "(e.g. 'BBL/process/0.20mm Standard @BBL A1M.json')")
    ap.add_argument("--out", type=Path, required=True,
                    help="output TOML path")
    args = ap.parse_args()

    root = args.root.resolve()
    leaf = (root / args.leaf).resolve()
    if not leaf.is_file():
        sys.exit(f"error: leaf not found: {leaf}")

    index = build_process_index(root)
    merged, chain = flatten_inheritance(leaf, index)

    name = leaf_display_name(leaf)
    merged.setdefault("print_settings_id", name)
    if not merged.get("print_settings_id"):
        merged["print_settings_id"] = name

    print(f"flattened {leaf.relative_to(root)}: {len(merged)} keys, chain depth {len(chain)}")
    for p in chain:
        print(f"  - {p.relative_to(root) if p.is_relative_to(root) else p}")

    write_toml(args.out, merged, source=leaf, chain=chain, root=root)
    print(f"\nwrote {args.out} ({len(merged)} keys)")


if __name__ == "__main__":
    main()
